"""Pre-defined symbol lists for simulation mode.

These mirror the naming convention used by OKX perpetual swaps
so that downstream code (Engine, Scheduler, FactorRuntime) can
work with the exact same symbol format as live trading.
"""

from __future__ import annotations

# Major perpetual swap contracts — commonly used subset.
DEFAULT_SYMBOLS: list[str] = [
    "BTC-USDT-SWAP",
    "ETH-USDT-SWAP",
    "SOL-USDT-SWAP",
    "DOGE-USDT-SWAP",
    "XRP-USDT-SWAP",
]

# Broader universe for stress / capacity testing (~100 symbols).
EXTENDED_SYMBOLS: list[str] = DEFAULT_SYMBOLS + [
    # --- Tier 1: Top 20 by market cap ---
    "BNB-USDT-SWAP",
    "ADA-USDT-SWAP",
    "AVAX-USDT-SWAP",
    "DOT-USDT-SWAP",
    "LINK-USDT-SWAP",
    "MATIC-USDT-SWAP",
    "UNI-USDT-SWAP",
    "ATOM-USDT-SWAP",
    "LTC-USDT-SWAP",
    "ARB-USDT-SWAP",
    "OP-USDT-SWAP",
    "APT-USDT-SWAP",
    "FIL-USDT-SWAP",
    "NEAR-USDT-SWAP",
    "SUI-USDT-SWAP",
    # --- Tier 2: Meme & AI & New L1/L2 ---
    "PEPE-USDT-SWAP",
    "WLD-USDT-SWAP",
    "SEI-USDT-SWAP",
    "TIA-USDT-SWAP",
    "INJ-USDT-SWAP",
    "FET-USDT-SWAP",
    "RENDER-USDT-SWAP",
    "STX-USDT-SWAP",
    "IMX-USDT-SWAP",
    "MKR-USDT-SWAP",
    "AAVE-USDT-SWAP",
    "GRT-USDT-SWAP",
    "ALGO-USDT-SWAP",
    "FTM-USDT-SWAP",
    "SAND-USDT-SWAP",
    # --- Tier 3: DeFi & Gaming & Infra ---
    "MANA-USDT-SWAP",
    "CRV-USDT-SWAP",
    "LDO-USDT-SWAP",
    "RUNE-USDT-SWAP",
    "EGLD-USDT-SWAP",
    "THETA-USDT-SWAP",
    "ICP-USDT-SWAP",
    "HBAR-USDT-SWAP",
    "VET-USDT-SWAP",
    "GALA-USDT-SWAP",
    "FLOW-USDT-SWAP",
    "AXS-USDT-SWAP",
    "EOS-USDT-SWAP",
    "KAVA-USDT-SWAP",
    "ZIL-USDT-SWAP",
    # --- Tier 4: Additional high-volume perps ---
    "TRX-USDT-SWAP",
    "SHIB-USDT-SWAP",
    "BCH-USDT-SWAP",
    "ETC-USDT-SWAP",
    "XLM-USDT-SWAP",
    "TON-USDT-SWAP",
    "KAS-USDT-SWAP",
    "TAO-USDT-SWAP",
    "JUP-USDT-SWAP",
    "PENDLE-USDT-SWAP",
    "W-USDT-SWAP",
    "STRK-USDT-SWAP",
    "ORDI-USDT-SWAP",
    "WIF-USDT-SWAP",
    "BONK-USDT-SWAP",
    "FLOKI-USDT-SWAP",
    "JTO-USDT-SWAP",
    "PYTH-USDT-SWAP",
    "DYM-USDT-SWAP",
    "MANTA-USDT-SWAP",
    "PIXEL-USDT-SWAP",
    "ENS-USDT-SWAP",
    "SNX-USDT-SWAP",
    "COMP-USDT-SWAP",
    "1INCH-USDT-SWAP",
    "DYDX-USDT-SWAP",
    "BLUR-USDT-SWAP",
    "MASK-USDT-SWAP",
    "SSV-USDT-SWAP",
    "CELO-USDT-SWAP",
    "ZRX-USDT-SWAP",
    "SUSHI-USDT-SWAP",
    "YFI-USDT-SWAP",
    "BAL-USDT-SWAP",
    "BAND-USDT-SWAP",
    "STORJ-USDT-SWAP",
    "REN-USDT-SWAP",
    "ANKR-USDT-SWAP",
    "CHZ-USDT-SWAP",
    "GMT-USDT-SWAP",
    "LINA-USDT-SWAP",
    "RSR-USDT-SWAP",
    "WAVES-USDT-SWAP",
    "NEO-USDT-SWAP",
    "QTUM-USDT-SWAP",
    "ONT-USDT-SWAP",
    "IOST-USDT-SWAP",
    "ZEC-USDT-SWAP",
    "DASH-USDT-SWAP",
    "XMR-USDT-SWAP",
    "ASTR-USDT-SWAP",
    "CFX-USDT-SWAP",
]

# Rough reference base prices (USD) for synthetic data generators.
# Only needs to be in the right order of magnitude.
SYMBOL_BASE_PRICES: dict[str, float] = {
    "BTC-USDT-SWAP": 85000.0,
    "ETH-USDT-SWAP": 3000.0,
    "SOL-USDT-SWAP": 150.0,
    "DOGE-USDT-SWAP": 0.15,
    "XRP-USDT-SWAP": 0.55,
    "BNB-USDT-SWAP": 600.0,
    "ADA-USDT-SWAP": 0.45,
    "AVAX-USDT-SWAP": 35.0,
    "DOT-USDT-SWAP": 7.0,
    "LINK-USDT-SWAP": 15.0,
    "MATIC-USDT-SWAP": 0.50,
    "UNI-USDT-SWAP": 7.0,
    "ATOM-USDT-SWAP": 9.0,
    "LTC-USDT-SWAP": 90.0,
    "ARB-USDT-SWAP": 1.10,
    "OP-USDT-SWAP": 1.80,
    "APT-USDT-SWAP": 8.0,
    "FIL-USDT-SWAP": 5.0,
    "NEAR-USDT-SWAP": 5.0,
    "SUI-USDT-SWAP": 3.5,
    "PEPE-USDT-SWAP": 0.000012,
    "WLD-USDT-SWAP": 2.5,
    "SEI-USDT-SWAP": 0.35,
    "TIA-USDT-SWAP": 8.0,
    "INJ-USDT-SWAP": 25.0,
    "FET-USDT-SWAP": 1.5,
    "RENDER-USDT-SWAP": 7.0,
    "STX-USDT-SWAP": 1.8,
    "IMX-USDT-SWAP": 1.5,
    "MKR-USDT-SWAP": 1500.0,
    "AAVE-USDT-SWAP": 90.0,
    "GRT-USDT-SWAP": 0.15,
    "ALGO-USDT-SWAP": 0.20,
    "FTM-USDT-SWAP": 0.40,
    "SAND-USDT-SWAP": 0.35,
    "MANA-USDT-SWAP": 0.35,
    "CRV-USDT-SWAP": 0.50,
    "LDO-USDT-SWAP": 1.8,
    "RUNE-USDT-SWAP": 4.0,
    "EGLD-USDT-SWAP": 35.0,
    "THETA-USDT-SWAP": 1.2,
    "ICP-USDT-SWAP": 12.0,
    "HBAR-USDT-SWAP": 0.08,
    "VET-USDT-SWAP": 0.03,
    "GALA-USDT-SWAP": 0.025,
    "FLOW-USDT-SWAP": 0.65,
    "AXS-USDT-SWAP": 6.0,
    "EOS-USDT-SWAP": 0.75,
    "KAVA-USDT-SWAP": 0.55,
    "ZIL-USDT-SWAP": 0.02,
    "TRX-USDT-SWAP": 0.12,
    "SHIB-USDT-SWAP": 0.000025,
    "BCH-USDT-SWAP": 350.0,
    "ETC-USDT-SWAP": 25.0,
    "XLM-USDT-SWAP": 0.12,
    "TON-USDT-SWAP": 5.5,
    "KAS-USDT-SWAP": 0.12,
    "TAO-USDT-SWAP": 400.0,
    "JUP-USDT-SWAP": 0.80,
    "PENDLE-USDT-SWAP": 5.0,
    "W-USDT-SWAP": 0.50,
    "STRK-USDT-SWAP": 1.20,
    "ORDI-USDT-SWAP": 40.0,
    "WIF-USDT-SWAP": 2.50,
    "BONK-USDT-SWAP": 0.000025,
    "FLOKI-USDT-SWAP": 0.00018,
    "JTO-USDT-SWAP": 3.0,
    "PYTH-USDT-SWAP": 0.40,
    "DYM-USDT-SWAP": 2.5,
    "MANTA-USDT-SWAP": 1.8,
    "PIXEL-USDT-SWAP": 0.40,
    "ENS-USDT-SWAP": 15.0,
    "SNX-USDT-SWAP": 2.5,
    "COMP-USDT-SWAP": 50.0,
    "1INCH-USDT-SWAP": 0.35,
    "DYDX-USDT-SWAP": 1.5,
    "BLUR-USDT-SWAP": 0.30,
    "MASK-USDT-SWAP": 3.0,
    "SSV-USDT-SWAP": 25.0,
    "CELO-USDT-SWAP": 0.70,
    "ZRX-USDT-SWAP": 0.35,
    "SUSHI-USDT-SWAP": 0.80,
    "YFI-USDT-SWAP": 7000.0,
    "BAL-USDT-SWAP": 3.0,
    "BAND-USDT-SWAP": 1.2,
    "STORJ-USDT-SWAP": 0.50,
    "REN-USDT-SWAP": 0.04,
    "ANKR-USDT-SWAP": 0.03,
    "CHZ-USDT-SWAP": 0.08,
    "GMT-USDT-SWAP": 0.15,
    "LINA-USDT-SWAP": 0.008,
    "RSR-USDT-SWAP": 0.006,
    "WAVES-USDT-SWAP": 1.5,
    "NEO-USDT-SWAP": 12.0,
    "QTUM-USDT-SWAP": 3.0,
    "ONT-USDT-SWAP": 0.22,
    "IOST-USDT-SWAP": 0.008,
    "ZEC-USDT-SWAP": 25.0,
    "DASH-USDT-SWAP": 28.0,
    "XMR-USDT-SWAP": 160.0,
    "ASTR-USDT-SWAP": 0.08,
    "CFX-USDT-SWAP": 0.15,
}

# Fallback price for unknown symbols.
DEFAULT_BASE_PRICE: float = 100.0
